[package]
name = "pkm-rs"
version = "0.1.0"
authors = ["zaksabeast <19464008+zaksabeast@users.noreply.github.com>"]
edition = "2021"

[dependencies]
num_enum = { version = "0.5", default-features = false }
binrw = { version = "0.13.3", default-features = false }
